# Generated by Django 3.2.4 on 2023-11-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_cliente',
            name='fecha_compra',
        ),
    ]
